name: Build and push container all images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0' # weekly refresh on Sunday at 1am
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yml'
      - '.github/workflows/matrix.yml'

jobs:
  build:
    name: Triggering Ruby ${{ matrix.ruby }} build
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']

    uses: zenjoy/docker-ruby/.github/workflows/build.yml@main
    with:
      ruby: ${{ matrix.ruby }}
